[package]
name = "nearby"
version = "0.1.0"
authors = ["Flavio <flavio@wisespace.io>"]
license = "MIT OR Apache-2.0"

description = "Scans all nearby wifi networks and the devices connected to each network"
keywords = ["wireless", "wifi", "dot11"]
documentation = "https://github.com/wisespace-io/nearby"
repository = "https://github.com/wisespace-io/nearby"
readme = "README.md"

[dependencies]
clap = "2.32"
pcap = "0.7.0"
radiotap = "1"
bytes = "0.4"
byteorder = "1"
error-chain = "0.12"